### ISSUE TITLE
Update canopy cover transformer for drone pipeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#130]
**Task to do**
Build, test, and deploy new gantry canopy cover transformer

**Reason**
The canopy cover algorithm has been updated

**Result**
A new canopy cover transformer is available for gantry pipeline

**Comment by Chris-Schnaufer** [comment]
1) Update the algorithm for the drone pipeline on a new branch: https://github.com/AgPipeline/drone-pipeline-environment/blob/9f07b384146f8d5e946d35ce53c823b6e68469bf/transformer-canopycover/algorithm_rgb.py#L50
2) Build a new Docker image
3) Get the test images from https://drive.google.com/file/d/1DP-L6KTt4Ai1iB2DVCcSdhntok79xdtl/view?usp=sharing
4) Create an experiment YAML file to use as metadata: 
```
%YAML 1.1
---
pipeline:
    studyName: '2018'
    season: '2018'
    germplasmName: Sorghum bicolor
    collectingSite: Testing
    observationTimeStamp: '2018-01-19T13:01:02-08:00'
```
3) Use one or more of the test images to calculate the new canopy cover (see https://github.com/AgPipeline/transformer-canopycover README for instructions, substituting image & file names as needed)
4) Check that CSV files are created and that they contain reasonable values
5) Checkin changes and create a pull request to merge into the `develop` branch
